JUnit version 4.12
................................E............................................
Time: 0.783
There was 1 failure:
1) test49(org.apache.commons.math.analysis.LaguerreSolver_ESTest)
org.apache.commons.math.MaxIterationsExceededException: Maximal number of iterations (100) exceeded
	at org.apache.commons.math.analysis.LaguerreSolver.solve(LaguerreSolver.java:326)
	at org.apache.commons.math.analysis.LaguerreSolver.solveAll(LaguerreSolver.java:225)
	at org.apache.commons.math.analysis.LaguerreSolver.solveAll(LaguerreSolver.java:190)
	at org.apache.commons.math.analysis.LaguerreSolver_ESTest.test49(LaguerreSolver_ESTest.java:890)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

FAILURES!!!
Tests run: 76,  Failures: 1

